name: Unit tests

on:
  push:
  pull_request:

jobs:
  python:
    name: pillow ${{ matrix.pillow-version }}.x & python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    continue-on-error: true
    container: python:${{ matrix.python-version }}
    strategy:
      matrix:
        pillow-version:  [ "1", "2", "2.7", "3", "4", "5" , "6", "7", "8", "9", "10" ]
        python-version:  [ "3.8", "3.11" ]
    steps:
      - uses: actions/checkout@v2
      - name: Update pip and install build
        run: python3 -m pip install --upgrade pip build
      - name: Create and source virtual environment
        run: |
          python3 -m venv .venv 
          . .venv/bin/activate
      - name: install pillow
        run: python3 -m pip install pillow==${{ matrix.pillow-version }}
      - name: install requirements
        run: python3 -m pip install -r requirements.txt
      - name: run tests
        run: python -m unittest
